export const Types = {
  FIRE: "Fire",
  WATER: "Water",
  GRASS: "Grass",
  FLYING: "Flying",
  ROCK: "Rock",
  GROUND: "Ground",
  ELECTRIC: "Electric",
  ICE: "Ice",
  BUG: "Bug",
  STEEL: "Steel",
  DRAGON: "Dragon",
  FAIRY: "Fairy",
  FIGHTING: "Fighting",
  GHOST: "Ghost",
  NORMAL: "Normal",
  PSYCHIC: "Psychic",
  DARK: "Dark",
  POISON: "Poison",
  NONE: "NONE",
};
